# Generated by Django 6.0.1 on 2026-01-25 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='status',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_type',
        ),
        migrations.AddField(
            model_name='visit',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='visit',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='visit',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='type_of_business',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('Umrah', 'Umrah'), ('Ziyarat', 'Ziyarat')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='visit',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.agency'),
        ),
    ]
